package commands

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/docker/docker/api/types/mount"
	"session-attested/internal/crypto"
	"session-attested/internal/docker"
	"session-attested/internal/state"
)

type startOut struct {
	SessionID     string `json:"session_id"`
	SessionDir    string `json:"session_dir"`
	WorkspaceHost string `json:"workspace_host"`
	MetaPath      string `json:"meta_path"`

	ContainerID     string `json:"container_id"`
	Image           string `json:"image"`
	ImageDigest     string `json:"image_digest,omitempty"`
	ContainerReused bool   `json:"container_reused,omitempty"`

	CollectorAuto    bool   `json:"collector_auto,omitempty"`
	CollectorLogPath string `json:"collector_log_path,omitempty"`
	CollectorPIDPath string `json:"collector_pid_path,omitempty"`

	AutoGeneratedSigningKey string `json:"auto_generated_signing_key,omitempty"`
	AutoGeneratedPublicKey  string `json:"auto_generated_public_key,omitempty"`
}

type stringSlice []string

func (s *stringSlice) String() string { return strings.Join(*s, ",") }
func (s *stringSlice) Set(v string) error {
	*s = append(*s, v)
	return nil
}

func RunStart(args []string) int {
	configPath, profile, _ := extractConfigArgs(args)

	resolved, err := applyConfigDefaults("start", args)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 2
	}
	args = resolved

	fs := flag.NewFlagSet("start", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)

	stateDir := fs.String("state-dir", state.DefaultStateDir().Root, "state dir")
	workspaceHost := fs.String("workspace-host", "", "workspace host path (default: ./workspace/<session_id> if empty)")
	jsonOut := fs.Bool("json", false, "output JSON")

	// Docker integration
	image := fs.String("image", "", "docker image (required)")
	name := fs.String("name", "", "docker container name (optional)")
	pull := fs.Bool("pull", false, "pull image before start")
	build := fs.Bool("build", false, "build image before start")
	reuseContainer := fs.Bool("reuse-container", false, "reuse existing container by --name if present (start if stopped); create if missing")
	buildContext := fs.String("build-context", "", "docker build context dir (default: --workspace-host)")
	dockerfile := fs.String("dockerfile", "Dockerfile", "dockerfile path in build context")
	autoCollect := fs.Bool("auto-collect", false, "start collector daemon in background (until-stop mode)")
	autoCollectSudo := fs.Bool("auto-collect-sudo", true, "run auto collector via sudo when not root")
	autoCollectWait := fs.Duration("auto-collect-wait", 5*time.Second, "wait for collector readiness (collector.pid)")
	autoCollectLog := fs.String("auto-collect-log", "", "collector log path (default: <session_dir>/collector.log)")
	injectSessionEnv := fs.Bool("inject-session-env", true, "inject ATTESTED_SESSION_ID into container login shell env (/etc/profile.d and /etc/environment)")
	mountAttestedBin := fs.Bool("mount-attested-bin", false, "bind-mount host attested binary into container")
	attestedBinHostPath := fs.String("attested-bin-host-path", "", "host path to attested binary (default: current executable)")
	attestedBinContainerPath := fs.String("attested-bin-container-path", "/usr/local/bin/attested", "container path for mounted attested binary")
	gitUserName := fs.String("git-user-name", "", "configure git user.name in container dev user at start")
	gitUserEmail := fs.String("git-user-email", "", "configure git user.email in container dev user at start")
	gitSSHKeyHostPath := fs.String("git-ssh-key-host-path", "", "host path to SSH private key for github.com (mounted read-only into container)")
	gitSSHKeyContainerPath := fs.String("git-ssh-key-container-path", "/home/dev/.ssh/id_github_attested", "container path for mounted SSH private key")
	cgroupParent := fs.String("cgroup-parent", "", "docker cgroup parent (optional). e.g. /attested/<session_id>")
	var envs stringSlice
	var publish stringSlice
	var buildArgs stringSlice
	fs.Var(&envs, "env", "env var (repeatable), e.g. --env K=V")
	fs.Var(&publish, "publish", "port publish (repeatable), e.g. --publish 127.0.0.1:2222:22/tcp")
	fs.Var(&buildArgs, "build-arg", "docker build arg (repeatable), e.g. --build-arg DEV_UID=1000")

	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *image == "" {
		fmt.Fprintln(os.Stderr, "error: --image is required")
		return 2
	}
	if *autoCollect && !isRoot() && *autoCollectSudo {
		if err := ensureSudoNonInteractiveAvailable("start --auto-collect"); err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			return 2
		}
	}

	st := state.StateDir{Root: *stateDir}

	attestSigningKeyPath, _, err := configStringValue(configPath, profile, "attest", "signing_key", "signing-key")
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 2
	}

	sessionID, err := state.NewSessionID()
	if err != nil {
		fmt.Fprintln(os.Stderr, "error: generate session id:", err)
		return 3
	}

	wsHost := *workspaceHost
	if wsHost == "" {
		// repo直下で完結させたい場合向け（sudo不要）
		wsHost = filepath.Join(st.Root, "workspaces", sessionID)
	}
	if absWS, err := filepath.Abs(wsHost); err == nil {
		wsHost = absWS
	} else {
		fmt.Fprintln(os.Stderr, "error: resolve workspace-host:", err)
		return 2
	}

	// Create directories
	if err := os.MkdirAll(st.SessionDir(sessionID), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "error: mkdir session dir:", err)
		return 3
	}
	if err := os.MkdirAll(wsHost, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "error: mkdir workspace:", err)
		return 3
	}
	autoPriv, autoPub, err := prepareRunArtifacts(st.Root, attestSigningKeyPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error: prepare run artifacts:", err)
		return 3
	}

	meta, err := state.NewMeta(sessionID, wsHost)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 2
	}
	containerStateDir := containerPathForHostPath(st.Root, wsHost, "/workspace")

	// Docker: run/start container
	cli, err := docker.NewClient()
	if err != nil {
		fmt.Fprintln(os.Stderr, "error: docker client:", err)
		return 3
	}
	if err := docker.Ping(context.Background(), cli); err != nil {
		fmt.Fprintln(os.Stderr, "error: docker daemon not reachable:", err)
		return 3
	}

	extraMounts, err := buildExtraContainerMounts(*mountAttestedBin, *attestedBinHostPath, *attestedBinContainerPath, *gitSSHKeyHostPath, *gitSSHKeyContainerPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 2
	}

	var runRes *docker.RunResult
	containerCreated := false
	containerReused := false

	if *reuseContainer {
		if strings.TrimSpace(*name) == "" {
			fmt.Fprintln(os.Stderr, "error: --reuse-container requires --name (or config commands.start.name)")
			return 2
		}
		existsCtr, err := docker.Exists(context.Background(), cli, *name)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error: inspect existing container:", err)
			return 3
		}
		if existsCtr {
			runRes, err = docker.StartExistingContainer(context.Background(), cli, *name)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error: docker start existing container:", err)
				return 3
			}
			containerReused = true
		}
	}

	if runRes == nil {
		exists, err := docker.ImageExists(context.Background(), cli, *image)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error: inspect image:", err)
			return 3
		}
		if !exists && *build {
			ctxDir := *buildContext
			if ctxDir == "" {
				ctxDir = wsHost
			}
			if _, err := os.Stat(filepath.Join(ctxDir, *dockerfile)); err != nil {
				fmt.Fprintln(os.Stderr, "error: dockerfile not found:", err)
				return 2
			}
			if _, err := docker.BuildImage(context.Background(), cli, docker.BuildOptions{
				Tag:        *image,
				ContextDir: ctxDir,
				Dockerfile: *dockerfile,
				Pull:       *pull,
				BuildArgs:  []string(buildArgs),
			}); err != nil {
				fmt.Fprintln(os.Stderr, "error: docker build:", err)
				return 3
			}
		}
		if !exists && !*build && *pull {
			if _, err := docker.EnsureImage(context.Background(), cli, *image, true); err != nil {
				fmt.Fprintln(os.Stderr, "error: docker pull:", err)
				return 3
			}
		}
		if !exists && !*build && !*pull {
			fmt.Fprintln(os.Stderr, "error: image not found locally; set --pull or --build")
			return 2
		}

		runRes, err = docker.RunDevContainer(context.Background(), cli, docker.RunOptions{
			Image:                  *image,
			Name:                   *name,
			WorkspaceHostPath:      wsHost,
			WorkspaceContainerPath: "/workspace",
			Env:                    withAttestedEnv([]string(envs), sessionID, containerStateDir, wsHost, "/workspace"),
			Publish:                []string(publish),
			Pull:                   false,
			CgroupParent:           *cgroupParent,
			TTY:                    true,
			Stdin:                  false,
			Labels:                 map[string]string{"attested.session_id": sessionID},
			ExtraMounts:            extraMounts,
		})
		if err != nil {
			fmt.Fprintln(os.Stderr, "error: docker run:", err)
			return 3
		}
		containerCreated = true
	}

	containerRollback := containerCreated
	startSucceeded := false
	defer func() {
		if startSucceeded {
			return
		}
		if containerRollback {
			rollbackContainerBestEffort(runRes.ContainerID, "start failed")
		} else if containerReused {
			// Reused containers may be shared across multiple sessions; do not remove on rollback.
			cli2, err := docker.NewClient()
			if err == nil {
				_ = docker.Stop(context.Background(), cli2, runRes.ContainerID)
			}
		}
	}()

	meta.Docker.ContainerID = runRes.ContainerID
	meta.Docker.Image = runRes.ImageName
	meta.Docker.ImageDigest = runRes.ImageDigest
	meta.Docker.Reused = containerReused

	if *injectSessionEnv {
		if err := docker.InjectSessionEnv(context.Background(), cli, runRes.ContainerID, sessionID, containerStateDir, "/workspace", wsHost); err != nil {
			fmt.Fprintln(os.Stderr, "error: inject session env into container:", err)
			return 3
		}
	}
	githubSSHKeyPathInContainer := ""
	if strings.TrimSpace(*gitSSHKeyHostPath) != "" {
		githubSSHKeyPathInContainer = *gitSSHKeyContainerPath
	}
	if err := docker.ConfigureDevGit(context.Background(), cli, runRes.ContainerID, docker.DevGitSetupOptions{
		UserName:            *gitUserName,
		UserEmail:           *gitUserEmail,
		GitHubSSHKeyPath:    githubSSHKeyPathInContainer,
		GitHubSSHConfigPath: "/home/dev/.ssh/config",
		DevUser:             "dev",
		DevHome:             "/home/dev",
	}); err != nil {
		fmt.Fprintln(os.Stderr, "error: configure dev git/ssh:", err)
		return 3
	}

	metaPath := st.MetaPath(sessionID)
	if err := state.WriteJSON(metaPath, meta, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "error: write meta:", err)
		return 3
	}
	if err := writeLastSessionID(sessionID); err != nil {
		fmt.Fprintln(os.Stderr, "warn: write last_session_id:", err)
	}
	chownPathToSudoOwnerBestEffort(filepath.Join(wsHost, ".attest_run"))

	collectorLogPath := ""
	collectorPIDPath := st.CollectorPIDPath(sessionID)
	if *autoCollect {
		logPath := *autoCollectLog
		if logPath == "" {
			logPath = filepath.Join(st.SessionDir(sessionID), "collector.log")
		}
		if err := startCollectorDaemon(sessionID, st.Root, logPath, *autoCollectSudo, *autoCollectWait); err != nil {
			fmt.Fprintln(os.Stderr, "error: auto collector:", err)
			return 3
		}
		collectorLogPath = logPath
	}
	containerRollback = false

	if *jsonOut {
		out := startOut{
			SessionID:       sessionID,
			SessionDir:      st.SessionDir(sessionID),
			WorkspaceHost:   wsHost,
			MetaPath:        metaPath,
			ContainerID:     runRes.ContainerID,
			Image:           runRes.ImageName,
			ImageDigest:     runRes.ImageDigest,
			ContainerReused: containerReused,
			CollectorAuto:   *autoCollect,
		}
		if autoPriv != "" {
			out.AutoGeneratedSigningKey = autoPriv
			out.AutoGeneratedPublicKey = autoPub
		}
		if collectorLogPath != "" {
			out.CollectorLogPath = collectorLogPath
			out.CollectorPIDPath = collectorPIDPath
		}
		enc := json.NewEncoder(os.Stdout)
		enc.SetEscapeHTML(false)
		_ = enc.Encode(out)
		startSucceeded = true
		return 0
	}

	fmt.Printf("session_id: %s\n", sessionID)
	fmt.Printf("session_dir: %s\n", st.SessionDir(sessionID))
	fmt.Printf("workspace_host: %s\n", wsHost)
	fmt.Printf("container_id: %s\n", runRes.ContainerID)
	fmt.Printf("image: %s\n", runRes.ImageName)
	if containerReused {
		fmt.Printf("container_reused: true\n")
	}
	if runRes.ImageDigest != "" {
		fmt.Printf("image_digest: %s\n", runRes.ImageDigest)
	}
	fmt.Printf("meta: %s\n", metaPath)
	if *autoCollect {
		fmt.Printf("collector_auto: true\n")
		fmt.Printf("collector_pid: %s\n", collectorPIDPath)
		fmt.Printf("collector_log: %s\n", collectorLogPath)
	} else {
		fmt.Println("collector_auto: false")
		fmt.Printf("next: run collector manually (requires sudo): %s collect --session %s --state-dir %s --until-stop\n", filepath.Base(exeOrFallback()), sessionID, st.Root)
	}
	if autoPriv != "" {
		fmt.Printf("generated_signing_key: %s\n", autoPriv)
		fmt.Printf("generated_public_key: %s\n", autoPub)
	}
	startSucceeded = true
	return 0
}

func withAttestedEnv(envs []string, sessionID, stateDir, workspaceHost, workspaceContainer string) []string {
	desired := map[string]string{
		"ATTESTED_SESSION_ID":               sessionID,
		"ATTESTED_STATE_DIR":                stateDir,
		"ATTESTED_WORKSPACE_HOST_PATH":      workspaceHost,
		"ATTESTED_WORKSPACE_CONTAINER_PATH": workspaceContainer,
	}
	out := make([]string, 0, len(envs)+1)
	for _, e := range envs {
		replaced := false
		for k, v := range desired {
			prefix := k + "="
			if strings.HasPrefix(e, prefix) {
				out = append(out, prefix+v)
				delete(desired, k)
				replaced = true
				break
			}
		}
		if replaced {
			continue
		}
		out = append(out, e)
	}
	for k, v := range desired {
		out = append(out, k+"="+v)
	}
	return out
}

func prepareRunArtifacts(stateDirRoot, configSigningKeyPath string) (privPath, pubPath string, err error) {
	// Convention: when state-dir is ".../<run_dir>/state", initialize sibling dirs.
	if filepath.Base(stateDirRoot) == "state" {
		runDir := filepath.Dir(stateDirRoot)
		keysDir := filepath.Join(runDir, "keys")
		attestDir := filepath.Join(runDir, "attestations")
		if err := os.MkdirAll(stateDirRoot, 0o755); err != nil {
			return "", "", err
		}
		if err := os.MkdirAll(keysDir, 0o755); err != nil {
			return "", "", err
		}
		if err := os.MkdirAll(attestDir, 0o755); err != nil {
			return "", "", err
		}
	}

	if strings.TrimSpace(configSigningKeyPath) != "" {
		privPath = configSigningKeyPath
	} else {
		if filepath.Base(stateDirRoot) != "state" {
			return "", "", nil
		}
		keysDir := filepath.Join(filepath.Dir(stateDirRoot), "keys")
		privPath = filepath.Join(keysDir, "attestation_priv.pem")
	}
	pubPath = inferPublicKeyPath(privPath)

	if err := os.MkdirAll(filepath.Dir(privPath), 0o755); err != nil {
		return "", "", err
	}
	if err := os.MkdirAll(filepath.Dir(pubPath), 0o755); err != nil {
		return "", "", err
	}

	if _, err := os.Stat(privPath); err == nil {
		// private exists: create public only if missing
		if _, err2 := os.Stat(pubPath); err2 == nil {
			return "", "", nil
		}
		priv, err := crypto.LoadEd25519PrivateKey(privPath)
		if err != nil {
			return "", "", err
		}
		if err := crypto.SaveEd25519PublicKey(pubPath, crypto.PublicFromPrivate(priv)); err != nil {
			return "", "", err
		}
		return "", "", nil
	}

	pub, priv, err := crypto.GenerateEd25519Keypair()
	if err != nil {
		return "", "", err
	}
	if err := crypto.SaveEd25519PrivateKey(privPath, priv); err != nil {
		return "", "", err
	}
	if err := crypto.SaveEd25519PublicKey(pubPath, pub); err != nil {
		return "", "", err
	}
	return privPath, pubPath, nil
}

func inferPublicKeyPath(privPath string) string {
	base := filepath.Base(privPath)
	dir := filepath.Dir(privPath)
	switch {
	case strings.Contains(base, "_priv."):
		return filepath.Join(dir, strings.Replace(base, "_priv.", "_pub.", 1))
	case strings.Contains(base, "-priv."):
		return filepath.Join(dir, strings.Replace(base, "-priv.", "-pub.", 1))
	default:
		return filepath.Join(dir, "attestation_pub.pem")
	}
}

func containerPathForHostPath(path, workspaceHost, workspaceContainer string) string {
	cleanPath := filepath.Clean(path)
	cleanWSHost := filepath.Clean(workspaceHost)
	if rel, err := filepath.Rel(cleanWSHost, cleanPath); err == nil && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		if rel == "." {
			return workspaceContainer
		}
		return filepath.ToSlash(filepath.Join(workspaceContainer, rel))
	}
	return cleanPath
}

func buildExtraContainerMounts(enableAttested bool, attestedHostPath, attestedContainerPath, gitSSHKeyHostPath, gitSSHKeyContainerPath string) ([]mount.Mount, error) {
	var out []mount.Mount
	if enableAttested {
		src := strings.TrimSpace(attestedHostPath)
		if src == "" {
			var err error
			src, err = os.Executable()
			if err != nil {
				return nil, fmt.Errorf("resolve attested binary path for mount: %w", err)
			}
		}
		if strings.TrimSpace(attestedContainerPath) == "" {
			return nil, fmt.Errorf("--attested-bin-container-path is empty")
		}
		if fi, err := os.Stat(src); err != nil {
			return nil, fmt.Errorf("attested binary mount source not found: %w", err)
		} else if fi.IsDir() {
			return nil, fmt.Errorf("attested binary mount source must be a file: %s", src)
		}
		out = append(out, mount.Mount{
			Type:     mount.TypeBind,
			Source:   src,
			Target:   attestedContainerPath,
			ReadOnly: true,
		})
	}

	if strings.TrimSpace(gitSSHKeyHostPath) != "" {
		if strings.TrimSpace(gitSSHKeyContainerPath) == "" {
			return nil, fmt.Errorf("--git-ssh-key-container-path is empty")
		}
		if fi, err := os.Stat(gitSSHKeyHostPath); err != nil {
			return nil, fmt.Errorf("git ssh key mount source not found: %w", err)
		} else if fi.IsDir() {
			return nil, fmt.Errorf("git ssh key mount source must be a file: %s", gitSSHKeyHostPath)
		}
		out = append(out, mount.Mount{
			Type:     mount.TypeBind,
			Source:   gitSSHKeyHostPath,
			Target:   gitSSHKeyContainerPath,
			ReadOnly: true,
		})
	}

	return out, nil
}

func exeOrFallback() string {
	exe, err := os.Executable()
	if err != nil || exe == "" {
		return "attested"
	}
	return exe
}

func startCollectorDaemon(sessionID, stateDir, logPath string, useSudo bool, wait time.Duration) error {
	exe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("resolve executable: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(logPath), 0o755); err != nil {
		return fmt.Errorf("mkdir collector log dir: %w", err)
	}
	logf, err := os.OpenFile(logPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return fmt.Errorf("open collector log: %w", err)
	}
	defer logf.Close()

	collectArgs := []string{
		"collect",
		"--session", sessionID,
		"--state-dir", stateDir,
		"--until-stop",
	}
	var cmd *exec.Cmd
	if useSudo && os.Geteuid() != 0 {
		sudoArgs := append([]string{"-n", exe}, collectArgs...)
		cmd = exec.Command("sudo", sudoArgs...)
	} else {
		cmd = exec.Command(exe, collectArgs...)
	}
	cmd.Stdout = logf
	cmd.Stderr = logf
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}

	if err := cmd.Start(); err != nil {
		return fmt.Errorf("start collector process: %w", err)
	}

	pidPath := state.StateDir{Root: stateDir}.CollectorPIDPath(sessionID)
	deadline := time.Now().Add(wait)
	for time.Now().Before(deadline) {
		if _, err := os.Stat(pidPath); err == nil {
			return nil
		}
		if cmd.ProcessState != nil && cmd.ProcessState.Exited() {
			break
		}
		if err := cmd.Process.Signal(syscall.Signal(0)); err != nil {
			break
		}
		time.Sleep(200 * time.Millisecond)
	}
	return fmt.Errorf("collector did not become ready; see log: %s", logPath)
}
