// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadExecLSM returns the embedded CollectionSpec for ExecLSM.
func LoadExecLSM() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecLSMBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ExecLSM: %w", err)
	}

	return spec, err
}

// LoadExecLSMObjects loads ExecLSM and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ExecLSMObjects
//	*ExecLSMPrograms
//	*ExecLSMMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadExecLSMObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadExecLSM()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ExecLSMSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecLSMSpecs struct {
	ExecLSMProgramSpecs
	ExecLSMMapSpecs
	ExecLSMVariableSpecs
}

// ExecLSMProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecLSMProgramSpecs struct {
	OnBprmCheckSecurity *ebpf.ProgramSpec `ebpf:"on_bprm_check_security"`
	OnSysEnterExecve    *ebpf.ProgramSpec `ebpf:"on_sys_enter_execve"`
	OnSysEnterExecveat  *ebpf.ProgramSpec `ebpf:"on_sys_enter_execveat"`
	OnSysEnterOpenat    *ebpf.ProgramSpec `ebpf:"on_sys_enter_openat"`
}

// ExecLSMMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecLSMMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// ExecLSMVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecLSMVariableSpecs struct {
}

// ExecLSMObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadExecLSMObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecLSMObjects struct {
	ExecLSMPrograms
	ExecLSMMaps
	ExecLSMVariables
}

func (o *ExecLSMObjects) Close() error {
	return _ExecLSMClose(
		&o.ExecLSMPrograms,
		&o.ExecLSMMaps,
	)
}

// ExecLSMMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadExecLSMObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecLSMMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *ExecLSMMaps) Close() error {
	return _ExecLSMClose(
		m.Events,
	)
}

// ExecLSMVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadExecLSMObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecLSMVariables struct {
}

// ExecLSMPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadExecLSMObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecLSMPrograms struct {
	OnBprmCheckSecurity *ebpf.Program `ebpf:"on_bprm_check_security"`
	OnSysEnterExecve    *ebpf.Program `ebpf:"on_sys_enter_execve"`
	OnSysEnterExecveat  *ebpf.Program `ebpf:"on_sys_enter_execveat"`
	OnSysEnterOpenat    *ebpf.Program `ebpf:"on_sys_enter_openat"`
}

func (p *ExecLSMPrograms) Close() error {
	return _ExecLSMClose(
		p.OnBprmCheckSecurity,
		p.OnSysEnterExecve,
		p.OnSysEnterExecveat,
		p.OnSysEnterOpenat,
	)
}

func _ExecLSMClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execlsm_bpfel.o
var _ExecLSMBytes []byte
